### ISSUE TITLE
Windows 10 Universal App package deployment is not working

### ISSUE THREAD

**Issue by WiniumLover** [2gis/Winium.StoreApps#117]
Hi Team,
Thanks for the framework for windows mobile platform. I just got into an issue when try to deploy the universal app for windows with the format "App3_1.0.6.0_x86_x64_arm.appxbundle". I could not deploy this file using our framework. Could you please help me on this.

**Comment by NickAb** [comment]
See https://github.com/2gis/Winium.StoreApps/issues/116. It might be related.

Please, try creating store package (`*.appx`) with x86 only and use it to deploy your application.

**Comment by WiniumLover** [comment]
Thanks Nick, I could able to create a package with .appx format but when I try to deploy the same in winium inspector or through our program, got the error message as shown below. Could you please advise me on this.
"message": "There is an error in XML document (2, 2)."
![error](https://cloud.githubusercontent.com/assets/16206777/11685483/63f359d4-9e9f-11e5-9ef9-699828c0942d.PNG)
![error1](https://cloud.githubusercontent.com/assets/16206777/11685492/6cb2a6ce-9e9f-11e5-8390-cab6d1868927.PNG)

**Comment by NickAb** [comment]
This is most likely because you are using 1.4.0 release. Support of UWP apps was added after 1.4.0 and is not yet released, but available in master.
But you can build driver from master branch yourself, it should work. I will try to make release ASAP (no later, then on next week)

**Comment by WiniumLover** [comment]
Perfect, thanks for the reply Nick.

**Comment by WiniumLover** [comment]
Hi Nick,
         I have download the latest package (.zip) from master and when I try to deploy the package in .appx format to winium inspector or through our code, got the issue #116 , even though after deleting the ARM and x64 directories from the AppPackages directories folder. could you please suggest me what I am missing here.

**Comment by NickAb** [comment]
Could you try not deleting files, but instead creating store package with x86 only.
Select **Store -> Create App Packages...**. In dialog window uncheck all architectures, except x86 in **Select the packages to create and the solution configuration mappings** section.

**Comment by WiniumLover** [comment]
yeah, I have done the same thing in Visual studio 2015 community edition but still it creates those folders.

**Comment by dnovikau** [comment]
Please see my last comment in #116.

**Comment by dnovikau** [comment]
Could you try not deleting files, but instead create store package with x86 only.
Select Store -> Create App Packages.... In dialog window uncheck all architectures, except x86 in Select the packages to create and the solution configuration mappings section.

**Comment by WiniumLover** [comment]
@dnovikau , so still you could not deploy even though you commented out the part rite.

**Comment by dnovikau** [comment]
if to remove x64 and ARM folders from 'dependencies' folder the deployment finishes successfully

**Comment by WiniumLover** [comment]
Cool, thanks for the info.

Also I have noticed that I have created .appxbundle for the windows 8.1 app and tried to deploy using the code, surprisingly it went fine without any issues. 

let me try for universal app and update you.

**Comment by WiniumLover** [comment]
ah strangely, when I try to deploy .appxbundle for universal app, end up with the below issue after commented the line suggested by @dnovikau and deleted other folders except x86 from dependencies folder.

2) Error : Samples.AutoSuggestSample.TestAutoSuggest
SetUp : System.InvalidOperationException : To install this application you need
either a Windows developer license or a sideloading-enabled system.
 (33)
![error2](https://cloud.githubusercontent.com/assets/16206777/11715104/4857a574-9f65-11e5-8d5e-e3bed7f74b24.PNG)

**Comment by dnovikau** [comment]
You need to enable 'developer mode' on your device -> then create 'Checkpoint' and make it default

**Comment by NickAb** [comment]
@dnovikau, thanks.

I guess I have done this while experimenting with `WinAppDeployCmd.exe` and forgot about it. But I am unable to confirm this at the moment, I will be able to check this on Monday only.

If this is a reason, then I will add some informative message for `"System.InvalidOperationException : To install this application you need either a Windows developer license or a sideloading-enabled system."`

**Comment by WiniumLover** [comment]
@dnovikau , I have already enabled developer mode on this but not sure why this giving the problem. Let  me create a new app package and will update you.

**Comment by WiniumLover** [comment]
@NickAb , @dnovikau , I noticed the strange thing that when I deploy the inbuilt test app with winium project through our code, it works fine but when I deploy the app created by me end up with issue  "System.InvalidOperationException : To install this application you need either a Windows developer license or a sideloading-enabled system." .

**Comment by NickAb** [comment]
@WiniumLover , could you please describe your setup.
As I understand you use Windows 10.

Do you have `Sideload apps` enabled in your host (dekstop) system? http://www.howtogeek.com/219651/windows-10-allows-you-to-sideload-universal-apps-just-like-android-does/

I tested UWP support on Windows 8.1 host system only. I did not test it on Windows 10. On Windows 10 it might require enabling both host system side loading and emulator developer mode.

@dnovikau @WiniumLover, if you are using Windows 10, could you please test the combinations of host side loading settings and emulator developer mode?

**Comment by WiniumLover** [comment]
@NickAb , thanks for the reply. I am using Win10 laptop with developer mode enabled. Developer mode is enabled both in Laptop and Emulator. Will check for side loading and update you.

Please note that I could able to deploy the demo app which is part of winium package without any issues.

**Comment by NickAb** [comment]
The demo app is Windows Phone 8.1 app. UWP 10 app is not distributed with Winium solution yet.

**Comment by WiniumLover** [comment]
@NickAb , thx for the detailed info. I have downloaded the master code again, setup a new project and tried to deploy the UWP app, surprisingly it went fine without any issues.

**Comment by NickAb** [comment]
@dnovikau does UWP deployment for Windows 10 Mobile works only with Developer mode enabled for you?

@WiniumLover are you able to deploy UWP app? If so I would like to close this issue.

I will keep #116 open until we sort out the dependencies problem.

**Comment by WiniumLover** [comment]
@NickAb , please feel free to close the issue. I could able to deploy UWP app without any issues.
