### ISSUE TITLE
Could not connect to the InnerServer issue for UWP app build with Caliburn.Micro

### ISSUE THREAD

**Issue by dnovikau** [2gis/Winium.StoreApps#119]
Prerequisites:
1. Universal windows application build by 'Caliburn.Micro' framework
2. The code 'AutomationServer.Instance.InitializeAndStart();' is added to the app after visual root is initialized:
![image](https://cloud.githubusercontent.com/assets/16187978/11711422/5fc99e16-9f37-11e5-8562-ed8981b6fbd2.png)
3. The app was successfully deployed to the emulator but failed on trying to connect to InnerServer with the following console output:
![image](https://cloud.githubusercontent.com/assets/16187978/11711536/2f1f6682-9f38-11e5-9861-81461042bbf3.png)

here is the place of code that attempted to fined the temp file (containing 'RemotePort' value if i'm not mistaken)
![image](https://cloud.githubusercontent.com/assets/16187978/11711701/676d882e-9f39-11e5-940a-f5e86d3bfc9e.png)

**Comment by NickAb** [comment]
Could you please try turning `Internet (Client & Server)` capability on? This might be a problem.
![image](https://cloud.githubusercontent.com/assets/866739/11775800/187376c6-a26c-11e5-89df-32fa3a3d3cc9.png)

In Windows 8.1 it worked with `Internet Client` only, but in UWP 10 apps it requires server capability.

**Comment by NickAb** [comment]
@dnovikau has setting `Internet (Client & Server)` capability solved your problem?

**Comment by dnovikau** [comment]
Sorry for long response, it seems that yes, maybe i did something else in addition to your proposal but in any case with this capability been checked right now I'm able to deploy the application and got response from InnerServer.

**Comment by NickAb** [comment]
Thanks, I will include this in README or wiki

**Comment by Pranodayd** [comment]
Hi @dnovikau and @NickAb 
I am facing similar issue on Windows 10 host system.I have Client&Server capability set in my application but still I am facing a problem.
@dnovikau can you please tell me which setting did the trick for you?
Note: I am able to connect to the instrumented innerserver on Windows 8 host system.
Thanks and Regards,
Pranoday
