### ISSUE TITLE
Alerts are not displayed in 'Inspector' and may not be interracted

### ISSUE THREAD

**Issue by dnovikau** [2gis/Winium.StoreApps#129]
1. In appropriate circumstances my AUT displays some alert over the main screen and waits the users interaction
2. Using the 'Winium.Inspector' i was not able to find displayed alert in the tree and as a result was not able to perform appropriate action
![image](https://cloud.githubusercontent.com/assets/16187978/12261914/363d3586-b935-11e5-8b21-40df5524c52d.png)

**Comment by NickAb** [comment]
`MessageDialog` is not attached to current window popups, but `ContentDialog` is.
The easiest way to work with alerts at the moment is to replace `MessageDialog` with `ContentDialog`.  

For example, in our test app I had
```cs
var noWifiDialog = new MessageDialog("Here's the content/string.", "Hello!")
{
Title = "No wifi connection",
Content = "Check connection and try again"
};
noWifiDialog.Commands.Add(new UICommand("Ok", this.CommandHandlers));
noWifiDialog.ShowAsync();
 ```
So I replaced it with:
```cs
var noWifiDialog = new ContentDialog()
{
Title = "No wifi connection",
Content = "Check connection and try again",
PrimaryButtonText = "Ok"
};
noWifiDialog.ShowAsync();
```

Now the ContentDialog is shown in `Winium.Inspector`. It's content is appended to the bottom of the tree. And now you can interact with it just like with the rest of interface.

This is how it can be done in python (which should be easy to translate to C#):
```py 
By.XNAME = 'xname'  # this is for example only, in real cases attach Automation Properties to buttons and use them to locate elements

dialog = self.driver.find_element_by_class_name('Windows.UI.Xaml.Controls.ContentDialog')
WpDriver to locate by xname in C#
print(dialog.find_element(By.XNAME, 'Title').text)  # not that it is preferred to attach AutomationProperties and use AutomationId or Name instead of xname
print(dialog.find_element(By.XNAME, 'Content').text)
 
dialog.find_element(By.XNAME, 'Button1Host').click()
```

**Comment by dnovikau** [comment]
Issue resolved by migrating to ContentDialog
