### ISSUE TITLE
Getting App Log

### ISSUE THREAD

**Issue by artemenko-a-a** [2gis/Winium.StoreApps#138]
When App crashes we don't have enough information about crash.
It seems cool to get an opportunity to get Log from App.
We store it in the root of local storage. It called "v4app.log.txt"

**Comment by NickAb** [comment]
Implemented in silverlight driver https://github.com/2gis/winphonedriver/pull/64

**Comment by NickAb** [comment]
Implemented in #140, but will work only if file is not open for writing at the time of command execution.

**Comment by NickAb** [comment]
Fixed in #140
