### ISSUE TITLE
How to write automation for appx file?

### ISSUE THREAD

**Issue by maninwindow** [2gis/Winium.StoreApps#139]
I am new for windows phone development and currently working on windows phone automation test.I only have appx file of the AUT,.My questions as follows:
1.Is it possible to automate appx files without source code?
2.If it is possible how to install appx file into windows phone emulator by writing code.
3.Is there any sample for this kind of automation?
Thanks in advance.

**Comment by NickAb** [comment]
It is not possible to automate the appx without embedding inner server in case of Winium.StoreApps.

You can automate the app without modification using Coded UI or Winium.StoreApps.CodedUi that wraps Coded UI. Coded UI will require Premium or equivalent license of Visual Studio.

**Comment by maninwindow** [comment]
Thank you very much. Let me try it with Winium.StoreApps.CodedUi .
