### ISSUE TITLE
Implement 'IsElementSelected' for 'RadioButton' class

### ISSUE THREAD

**Issue by dnovikau** [2gis/Winium.StoreApps#141]
![image](https://cloud.githubusercontent.com/assets/16187978/14704941/de165a98-07bf-11e6-9022-f6f7a38222da.png)

Is there any way to find out whether radio button element is 'Selected' or not? I need to know the state of radio button to apply appropriate strategy in my test scenario

**Comment by NickAb** [comment]
`IsElementSelected` is not implemented yet.

For a qucik fix you can use `GetElementAttribute` https://github.com/2gis/Winium.StoreApps/wiki/Supported-Commands#getelementattribute to get any property of element. I think you can use `IsChecked` property. Make sure to enable property access in session desired capabilities according to the link.

**Comment by dnovikau** [comment]
Provided solution is fully working
