### ISSUE TITLE
A step to step installation 

### ISSUE THREAD

**Issue by jiajiang09** [2gis/Winium.StoreApps#142]
Hi, NickAb
I saw you have a lot of contributions on Winium, I do like your tools and saw all your post related to that. Right now, i want to install it in my windows machine and start to use it. I am really new on Windows 10, don't know how to do it, so can you provide a step to step installation on how to install your tool

Thanks so much

**Comment by NickAb** [comment]
1. Make sure that your system meets requirements for Hyper-V and running emulators (you can find more info on [msdn](https://msdn.microsoft.com/en-us/library/windows/apps/ff626524(v=vs.105).aspx) in requirements article for WP 8, but it should be similar to 8.1).
2. You will need to install Visual Studio 2015 with Emulators.
3. Try deploying your app to emulator using `Windows Phone Application Deployment` app, which comes as part of SDK
4. Download latest Winium.StoreApps [release](https://github.com/2gis/Winium.StoreApps/releases/latest)

You environment should be ready.

**Comment by jiajiang09** [comment]
OK, i will use emulator to do the test. For your Winum.StoreApps release, after download, unpack these three package. What should i do next? Follow https://github.com/2gis/Winium.StoreApps/ Quick Start part to followup? what do you mean by add reference to Winum.StoreApps.InnerServer in AUT project?
Sorry about so many questions, i am still not that clear. Hope you can give more detail info on how to bring it up

Thanks

**Comment by NickAb** [comment]
Yes, you just need to run Winium.StoreApps.Driver.exe and follow quick start. AUT stand for app under a test. To use this version of driver you must have accesses to source code of app you want to test, as you will have to add automation server into it.

To do so, you have to add reference to Winium.StoreApps.InnerServer into the app you want to test. It can be done manually or using nuget as described in quick start. Then you will have to init automation server somewhere in your app, it can be done in MainPageOnLoaded, but actual place might vary if you use different frameworks.

You can also see samples and tests in the repos to get the ida how it works.
