### ISSUE TITLE
Error:"To install this application you need either a Windows developer license or a sideloading-enabled system." while installing Windows 10 application with dependencies

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.StoreApps#143]
Getting an error:"To install this application you need either a Windows developer license or a sideloading-enabled system." while installing Windows 10 application on emulator through Winium Driver if "Depencencies" capability is set.

Application gets installed successfully if "Dependencies" capability is not used.

Thanks and Regards,
Pranoday

**Comment by NickAb** [comment]
Do you need to deploy dependencies for app to work or does it work as is?

Are you using Windows 10 (desktop as your host system?
If so, you can try enabling developer mode on host system.
If it is not enough, only then try enabling developer mode on emulator https://msdn.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development#whichsettings

Note that emulator does not persist state by default ,so if updating emulator settings is a must, then you will need to create a checkpoint and set is as default checkpoint.
