### ISSUE TITLE
Not able to launch app on simulator/deploying it on same OS.

### ISSUE THREAD

**Issue by padmaja2812** [2gis/Winium.StoreApps#144]
Can you please share how i can install store app on tablet or as a desktop app from winium.

**Comment by NickAb** [comment]
Winium.StoreApps works for Windows Phone or Windows Mobile only. Tablets and desktop are not supported.
Winium.Desktop can be used for testing on desktop,  but it does not support modern apps yet https://github.com/2gis/Winium.Cruciatus/issues/53
