### ISSUE TITLE
 Error-There is an error in XML document (2,2) in deployment tool.

### ISSUE THREAD

**Issue by padmaja2812** [2gis/Winium.StoreApps#145]
Hi,
After creating package windows 10 with x86.
I am having appxbundle file which is giving same error "A packaging error prevented this application from installing."
With .appx file Error-There is an error in XML document (2,2). with deployment tool as well.
Can you please provide a way around for the same.

**Comment by NickAb** [comment]
`XML document (2,2).` should have been fixed in v1.5.0. What version of driver do you use?

**Comment by padmaja2812** [comment]
1.6 the latest version.

**Comment by padmaja2812** [comment]
Hi Nick,
The previous app i was able to deploy using deployment tool.
But when i tried with winium,it gave same error.
Meanwhile, I am able to automate the app with setting the "debugRunningApp"="true" in capabilities.
Can you help with this?

Thanks
Padmaja

**Comment by NickAb** [comment]
`debugConnectToRunningApp` completely skips the deployments steps and connects to already running app on the emulator.

Do I understand correctly that when you deploy your app using WinAppDeploy tool the deployment is successful, but when you are trying to deploy the same app using Winium, then `There is an error in XML document (2,2)` exception is raised?

**Comment by padmaja2812** [comment]
Yes.

**Comment by NickAb** [comment]
Please see #116, steps described in it might help.

**Comment by padmaja2812** [comment]
I am able to launch with help of #116 

Thanks for help :+1:
