### ISSUE TITLE
The server threw an exception

### ISSUE THREAD

**Issue by naix86** [2gis/Winium.StoreApps#150]
Hi Nick,

Now I keep getting this server exception thingy.

-------------------------------

17:21:20 [DEBUG] RESPONSE:
OK:
{
  "sessionId": "7bf6904c-af0d-458c-8d22-207f068a3a34",
  "status": 33,
  "value": {
    "error": "session not created",
    "stacktrace": "   at Winium.StoreApps.Driver.CommandExecutors.NewSessionExecutor.DoImpl() in d:\\Projects\\windows-universal-app-driver\\Winium\\Winium.StoreApps.Driver\\CommandExecutors\\NewSessionExecutor.cs:line 38\r\n   at Winium.StoreApps.Driver.CommandExecutors.CommandExecutorBase.Do() in d:\\Projects\\windows-universal-app-driver\\Winium\\Winium.StoreApps.Driver\\CommandExecutors\\CommandExecutorBase.cs:line 42",
    "message": "The server threw an exception. (Exception from HRESULT: 0x80010105 (RPC_E_SERVERFAULT))"
  }
}

**Comment by NickAb** [comment]
Duplicates #146
