### ISSUE TITLE
How to handle Windows MobileOS popups

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.StoreApps#152]
Hi @NickAb .
I am using Winium.StoreApps for automating our Windows 10 mobile application.I have a question:As Winium.StopreApps work on the principle of Application Instrumentation,so should it be able to spy Mobile OS popups?I think it should not as it is not the part of instrumented application,this is what currently happening.

Now I want to wait till popup appears and then close it.
How to achieve this using Winium.StoreApps as it does not have any controls outside the instrumented application.
Please help.
Thanks and Regards,
Pranoday

**Comment by Pranodayd** [comment]
Hi @NickAb .
I am using Winium.StoreApps for automating our Windows 10 mobile application.I have a question:As Winium.StopreApps work on the principle of Application Instrumentation,so should it be able to spy Mobile OS popups?I think it should not as it is not the part of instrumented application,this is what currently happening.

Now I want to wait till popup appears and then close it.
How to achieve this using Winium.StoreApps as it does not have any control on UI elements outside the instrumented application.
Please help.
Thanks and Regards,
Pranoday

**Comment by NickAb** [comment]
Any OS popups and `MessageDialog` (which can be shown by app, but is not attached to app's UI tree can not be found or interacted directly by driver). See similarhttps://github.com/2gis/Winium.StoreApps/issues/129. Solution, if available, is to replace any `MessageDialog` in your app with `ContentDialog` (which can be accessed by driver).
