### ISSUE TITLE
How to use Xname Stratergy to find elements?

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.StoreApps#156]
Hi @NickAb .
How can I use Xname element finding stratergy?Can I use xname as an attribute in Xpath?
I tried using xname in xpath but didn't work.
My xpath looks like this:
//*[@class_name='' and @xname='']

Please help

**Comment by NickAb** [comment]
XPath locators are not supported yet. Use of `x:Name` depends on the language you use to write tests.

For example in python one can simple do
```
from selenium.webdriver.common.by import By

By.XNAME = 'xname'
```

But in C# standard locators can not be extended that way, so one would something similar to implementation in https://github.com/2gis/Winium.StoreApps/blob/master/Winium/TestApp.Test/Samples/WpDriver.cs#L67

**Comment by Pranodayd** [comment]
@NickAb 
I am using java.How can I use Xname locator strategy in Java?

**Comment by NickAb** [comment]
I do not know for sure, but this https://mguillem.wordpress.com/2011/10/06/webdriver-subclass-the-by-class-to-define-own-locators/ might help

**Comment by Pranodayd** [comment]
Hi @NickAb 
Can I get value of Xname property using getAttribute() function?

**Comment by NickAb** [comment]
Yes, it should be exposed as `xname` attribute

**Comment by Pranodayd** [comment]
Ok.Thanks.I will try using this technique then.

**Comment by Pranodayd** [comment]
@NickAb 
getAttribute("xname"); returning me a null.
Why?Any idea?

**Comment by NickAb** [comment]
@Pranodayd where you able to find elements by `x:Name`?

**Comment by Pranodayd** [comment]
@NickAb 
Yes I could locate the element by x:Name.Thanks
