### ISSUE TITLE
Add support for Toggle pattern

### ISSUE THREAD

**Issue by NickAb** [2gis/Winium.StoreApps#22]
AppBarToggleButton does not support invoke pattern and could not be clicked due to AppBar coordinates mixup.

Add support for TogglePattern via `ExecuteScript ` with `automation: toggle`.
See more at [msdn](https://msdn.microsoft.com/en-us/library/system.windows.automation.togglepattern(v=vs.110).aspx)

**Comment by hepivax** [comment]
Hi NickAb,
Can you add an example that checks if ToggleState is On/Off?

Thanks,
hepivax

**Comment by NickAb** [comment]
Examples on how to read current toggle state can be found [in tests](https://github.com/2gis/Winium.Mobile/blob/master/Winium/TestApp.Test/py-functional/tests/test_commands.py#L270) and [in wiki](https://github.com/2gis/Winium.Mobile/wiki/Command-Execute-Script#use-automationpeerspatterninterface-on-element)

```py
element = self.driver.find_element_by_id("FirstToggleAppBarButton")
start_state = self.driver.execute_script("automation: TogglePattern.ToggleState", element)
```

**Comment by hepivax** [comment]
I've tried to use it, but I get "unknown script command" exception, any ideas?

`section_expand_state = self.desktop.execute_script("automation: TogglePattern.ToggleState", section_expand)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unknown script command 'automation: TogglePattern.ToggleState'. See https://github.com/2gis/Winium.Desktop/wiki/Command-Execute-Script#use-ui-automation-patterns-on-element for supported commands.`

**Comment by NickAb** [comment]
Do you use StoreApps or Silverlight version of InnerServer? What version of Driver.exe and InnerServer do you use?

**Comment by hepivax** [comment]
I'm sorry I didn't notice that this issue is related to Winium.Mobile.
I'm using Winium.Desktop server v1.6.0.
Is this fuctionality is planed to be added to the next desktop version?

**Comment by NickAb** [comment]
With Winium.Desktop you can simple use `IsElementSelected` to check if element is selected or toggled on. And to switch a state of an element you can try using `Click` command.
Maybe @skyline-gleb can provide more details.

**Comment by hepivax** [comment]
Thanks, works well for me.

**Comment by hepivax** [comment]
Hi @skyline-gleb,
I'm trying to check element is in read only state - how can I do that?
![image](https://cloud.githubusercontent.com/assets/18057615/22402967/1312e294-e612-11e6-8e53-83bcd2a1325d.png)
