### ISSUE TITLE
Add port discovery and make innerPort dynamic

### ISSUE THREAD

**Issue by NickAb** [2gis/Winium.StoreApps#39]
Making `innerPort` dynamically assignable from predefined range and including `innerPort` auto-discovery will greatly simplify parallel execution of tests on different emulators.

Currently to run tests in parallel on same machine one would have to:
1. build *n* copies of `.appx`, but with different innerPorts,
2. start *n* copies of driver,
3. start *n* sessions against each driver with different `innerPort` capability.

All this hassle with `innerPort` is caused by the fact that emulators do forward their port to localhost. Maybe there is another way to deal with it, for example modifying Hyper-V machine settings or switch in someway, but it seems more invasive.

Adding port discovery will let us get rid of step 1 completely and simplify step 3.

**Comment by hcorigliano** [comment]
+1 Upvote!!

**Comment by NickAb** [comment]
Replacing `BindServiceNameAsync` with `BindEndpointAsync` might limit port binding to only one network interface, instead of binding to all interfaces. As a result, there would be no more conflict between two different emulators using same port for `InnerServer`, bringing us one step closer to easy parallel sessions. But it needs some research.
