### ISSUE TITLE
Add support for Selenium Grid

### ISSUE THREAD

**Issue by NickAb** [2gis/Winium.StoreApps#91]
Add command line option to register the driver as a node for Selenium Grid

**Comment by nwlunatic** [comment]
Is it possible to use driver as standalone executable?
If so, maybe register driver via plugin to selenium-server-standalone would be much easier to implement. 
Example: https://github.com/nwlunatic/qtwebkitdriver-plugin

**Comment by NickAb** [comment]
Creating plugin will be considered if custom behavior or dc matching will be needed.
